<?php namespace ProcessWire ?>
<?php require_once('vendor/autoload.php');?>
<?php

use Facebook\InstantArticles\Elements\InstantArticle;

class  MarkupRSSFacebookInstantArticles extends WireData implements Module, ConfigurableModule{

	public static function getModuleInfo() {
		return array(
			'title' => "MarkupRSSFacebookInstantArticles",
			'version' => "0.0.1",
			'summary' => "",
			
			'author' => "",
			'href' => "",
			
			'permission' => array(""),
			'autoload' => false,
			'singular' => false,
			'permanent' => false,
			
			'requires' => array("PHP>=5.6", "ProcessWire>=3.0.47", ""),
			'installs' => array(""),
			
		);
	}

	public function init() {

		// $this->addStyle("custom.css");
		// $this->addScript("custom.js");
		// $this->addHookAfter("class::function", $this, "yourFunction");
	}

    public function render(){
        //$rules_file_content = file_get_contents("simple-rules.json", true);
        //$this->log(class_exists("Facebook\InstantArticles\Elements\InstantArticle"));
        $instant_article = InstantArticle::create();
    }
    

}